name: Sync Obsidian Notes to MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Copy files to MkDocs branch
        run: |
          git config --global user.email "manuel.schuelein@proton.me"
          git config --global user.name "deadmade"
          git checkout mkdocs || git checkout -b mkdocs
          rsync -av --exclude '.git' --exclude '.obsidian' --exclude '.gitignore' --exclude '.gitattributes' --exclude '.github' ./ ./docs/
          git add docs/
          git commit -m "Sync notes from main branch"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/deadmade/Tinf2023-LessonSummaries.git mkdocs --force
