name: Sync Obsidian Notes to MkDocs

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Copy files to MkDocs branch
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git checkout mkdocs || git checkout -b mkdocs
          rsync -av --exclude '.git' --exclude '.obsidian' --exclude '.gitignore' --exclude '.gitattributes' --exclude '.github' ./ ./docs/
          git add docs/
          git commit -m "Sync notes from main branch"
          git push origin mkdocs --force
        env:
          # Use the correct GitHub token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
