name: Sync Obsidian Notes to MkDocs

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Copy files to MkDocs branch
        run: |
          git config --global user.email "manuel.schuelein@proton.me"
          git config --global user.name "deadmade"
          git checkout mkdocs || git checkout -b mkdocs
          rsync -av --exclude '.git' ./ ./docs/
          git add docs/
          git commit -m "Sync notes from main branch"

      - name: Push to mkdocs branch
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/deadmade/Tinf2023-LessonSummaries.git
          git push origin mkdocs --force
